package com.floatinity.emp.exception;

public enum EMPError {

	EMP_APPLICATION_ERROR(1001, "EMP_APPLICATION_ERROR"), //
	EMP_DB_ERROR(1002, "EMP_DB_ERROR"), //
	EMP_ERR_HTTP_SERVER_ERROR(1003, "EMP_ERR_HTTP_SERVER_ERROR"), //
	EMP_ERR_INVALID_PAYLOAD(1004, "EMP_ERR_INVALID_PAYLOAD"), //
	EMP_ERR_INVALID_HTTP_METHOD(1005, "EMP_ERR_INVALID_HTTP_METHOD"), //
	EMP_ERR_INVALID_RESPONSE(1006, "EMP_ERR_INVALID_RESPONSE"), //
	EMP_ERR_VALIDATION_FAILED(1007, "EMP_ERR_VALIDATION_FAILED"), //
	EMP_ERR_PERMISSION_DENIED(1008, "EMP_ERR_PERMISSION_DENIED"), //
	EMP_ERR_TOKEN_AUTH_FAILURE(1009, "EMP_ERR_TOKEN_AUTH_FAILURE"), //
	EMP_ERR_INVALID_SESSION(1010, "EMP_ERR_INVALID_SESSION"), //
	EMP_ERR_USERNAME_INVALID(1011, "EMP_ERR_USERNAME_INVALID"), //
	EMP_ERR_PASSWORD_INVALID(1012, "EMP_ERR_PASSWORD_INVALID"), //
	EMP_ERR_USER_DOES_NOT_EXIST(1013, "EMP_ERR_USER_DOES_NOT_EXIST"), //
	EMP_ERR_USER_DOES_NOT_HAVE_LOGIN_ACCESS(1014, "EMP_ERR_USER_DOES_NOT_HAVE_LOGIN_ACCESS"),
	EMP_ERR_USER_EMAIL_INVALID(1015, "EMP_ERR_USER_EMAIL_INVALID"), //
	EMP_ERR_USER_CREATION_FAILED(1016, "EMP_ERR_USER_CREATION_FAILED"), //
	EMP_ERR_INVALID_TOKEN(1017, "EMP_ERR_INVALID_TOKEN"), //
	EMP_ERR_OLD_PASSWORD_INVALID(1018, "EMP_ERR_OLD_PASSWORD_INVALID"), //
	EMP_ERR_NEW_PASSWORD_INVALID(1019, "EMP_ERR_NEW_PASSWORD_INVALID"), //
	EMP_ERR_INVALID_PASSWORD_COMBINATION(1020, "EMP_ERR_INVALID_PASSWORD_COMBINATION"), //
	EMP_ERR_USER_RESET_PASS_FAILED(1021, "EMP_ERR_USER_RESET_PASS_FAILED"), //
	EMP_ERR_USER_NOT_ACTIVE(1022, "EMP_ERR_USER_NOT_ACTIVE"), //
	EMP_ERR_USER_ALREADY_EXIST_WTIH_THIS_EMAIL(1023, "EMP_ERR_USER_ALREADY_EXIST_WTIH_THIS_EMAIL"), //
	EMP_ERR_USER_ROLE_MAP_EMPTY(1024, "EMP_ERR_USER_ROLE_MAP_EMPTY"), //

	EMP_ERR_INVALID_ID(1025, "EMP_ERR_INVALID_ID"), //
	EMP_ERR_EMPLOYEE_ALREADY_EXIST_WTIH_THIS_EMAIL(1025, "EMP_ERR_EMPLOYEE_ALREADY_EXIST_WTIH_THIS_EMAIL"), //
	EMP_ERR_DEPARTMENT_ALREADY_EXIST(2026, "EMP_ERR_DEPARTMENT_ALREADY_EXIST"),
	EMP_ERR_INVALID_LEAVE_(2027, "Invalid Leave ID"),
	EMP_ERR_FILE_EMPTY_(2028, "FILE EMPTY"),
	

	;

	private int errCode;

	private String errKey;

	EMPError(int errorCode, String errorKey) {
		this.errCode = errorCode;
		this.errKey = errorKey;
	}

	public static EMPError forValue(String value) {
		for (EMPError error : values()) {
			if (error.getErrKey().equalsIgnoreCase(value)) {
				return error;
			}
		}
		return null;
	}

	public int getErrCode() {
		return errCode;
	}

	public void setErrCode(int errCode) {
		this.errCode = errCode;
	}

	public String getErrKey() {
		return errKey;
	}

	public void setErrKey(String errKey) {
		this.errKey = errKey;
	}

}
